export enum Configuration {
  APLICATION_PORT = 'PORT',
  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_USERNAME = 'POSTGRES_USERNAME',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DATABASE = 'POSTGRES_DATABASE',
  SECRET_KEY = 'SECRET_KEY',
  DEFAULT_ADMIN_USER = 'DEFAULT_ADMIN_USER',
  DEFAULT_ADMIN_PASSW = 'DEFAULT_ADMIN_PASSW',
  DEFAULT_ADMIN_email = 'gilbert@gmail.com',
}
